# Generated by Django 3.2.15 on 2022-12-16 14:39

from django.db import migrations

import api.images.models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file",
            field=api.images.models.ResizableImageField(upload_to="images/"),
        ),
    ]
